name: production

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  aws_cdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        if: contains(github.event_name, 'push')
        uses: actions/checkout@v2

      - name: Setup Node
        if: contains(github.event_name, 'push')
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Setup dependencies
        if: contains(github.event_name, 'push')
        run: npm run setup

      - name: Build
        if: contains(github.event_name, 'push')
        run: npm run build
        env:
          ENV: production

      - name: CDK Diff Check
        if: contains(github.event_name, 'push')
        run: npm run cdk:diff
        env:
          ENV: production
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: rm -rf ./node_modules && rm -rf ./src/node_modules && npm run setup:production && npm install -g aws-cdk && cdk bootstrap && cdk deploy --require-approval never
        env:
          ENV: production
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}